accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

articles/urls.py
from django.urls import path
from . import views
from django.urls import path, re_path

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    re_path('^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/',views.about, name='about'),
    path('', article_views.article_list, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,default=None, on_delete=models.CASCADE)
    # add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form' : form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, "articles/article_list.html", {'articles': articles})

def article_detail(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

djangoblog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("homepage")
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse("about")
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="translucent-form-overlay">
  <form  action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <h3 class="box-title">Login</h3>
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}" />
    {% endif %}
    <div class="row columns">
     {{form}}
     <input type="submit" class="green-button button expanded search-button" value="Login"/>
    </div>

    
      
 </form>
</div>



{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="translucent-form-overlay">
    <form  action="/accounts/signup/" method="post">
      {% csrf_token %}
      <h3 class="box-title">Signup</h3>
      <div class="row columns">
       {{form}}
       <input type="submit" class="green-button button expanded search-button" value="Signup"/>
      </div>   
   </form>
  </div>
  
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="translucent-form-overlay">
  <form  action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h3 class="box-title">Create an Awesome New Article</h3>
    <div class="row columns">
      {{form}}
      <input type="submit" class="green-button button expanded search-button" value="Create"/>
    </div>   
  </form>
</div>
  
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="row">
    <div class="medium-6 columns">
       <img class="thumbnail" src="{{article.thumb.url}}">
    </div>
    <div class="medium-6 large-5 columns">
      <h3>{{article.title}}</h3>
      <p>{{article.body}}</p>
      <p>{{article.date}}</p>
    </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="row column">
    <h4 style="margin: 0;" class="text-center">LATEST ARTICLES</h4>
  </div>
  <hr>
  <div class="row">
    <div class="large-8 columns" style="border-right: 1px solid #E3E5E8;">
        <article>
          {% for article in articles %}
          <div class="row">
              <div class="large-6 columns">
                <p><img src="{{article.thumb.url}}" alt="{{ article.title }}"></p>
              </div>
              <div class="large-6 columns">
                <h5><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h5>
                <p>
                    <span><i class="fi-torso"> By {{ article.author.username}} &nbsp;&nbsp;</i></span>
                    <span><i class="fi-calendar"> {{ article.date }} &nbsp;&nbsp;</i></span>
                    <span><i class="fi-comments"> 6 comments</i></span>
                </p>
                <p>{{ article.snippet }}</p>
              </div>
          </div>
          <hr>
          {% endfor %}
          <ul class="pagination" role="navigation" aria-label="Pagination">
              <li class="disabled">Previous <span class="show-for-sr">page</span></li>
              <li class="current"><span class="show-for-sr">You're on page</span> 1</li>
              <li><a href="#" aria-label="Page 2">2</a></li>
              <li><a href="#" aria-label="Page 3">3</a></li>
              <li><a href="#" aria-label="Page 4">4</a></li>
              <li><a href="#" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
          </ul>
        </article>
    </div>
    <div class="large-4 columns">
        <aside>
          <div class="row small-up-3">
              <div class="column text-center">
                <i class="fi-social-facebook"></i>
                <h6>56,009</h6>
                <p><small>FOLLOWERS</small></p>
                <br>
              </div>
              <div class="column text-center">
                <i class="fi-social-twitter"></i>
                <h6>76,905</h6>
                <p><small>FOLLOWERS</small></p>
                <br>
              </div>
              <div class="column text-center">
                <i class="fi-social-instagram"></i>
                <h6>34,099</h6>
                <p><small>FOLLOWERS</small></p>
                <br>
              </div>
              <div class="column text-center">
                <i class="fi-social-tumblr"></i>
                <h6>13,765</h6>
                <p><small>FOLLOWERS</small></p>
              </div>
              <div class="column text-center">
                <i class="fi-social-pinterest"></i>
                <h6>9,283</h6>
                <p><small>FOLLOWERS</small></p>
              </div>
              <div class="column text-center">
                <i class="fi-social-youtube"></i>
                <h6>99,000</h6>
                <p><small>FOLLOWERS</small></p>
              </div>
          </div>
          <br>
          <div class="row column">
              <p class="lead">FROM OUR FRIENDS</p>
              <p><img src="https://placehold.it/400x300&amp;text=Buy Me!" alt="advertisement of ShamWow"></p>
          </div>
          <br>
          <div class="row column">
              <p class="lead">TRENDING POSTS</p>
              <div class="media-object">
                <div class="media-object-section">
                    <img class="thumbnail" src="https://placehold.it/100">
                </div>
                <div class="media-object-section">
                    <h5>All I need is a space suit and I'm ready to go.</h5>
                </div>
              </div>
              <div class="media-object">
                <div class="media-object-section">
                    <img class="thumbnail" src="https://placehold.it/100">
                </div>
                <div class="media-object-section">
                    <h5>Are the stars out tonight? I don't know if it's cloudy or bright.</h5>
                </div>
              </div>
              <div class="media-object">
                <div class="media-object-section">
                    <img class="thumbnail" src="https://placehold.it/100">
                </div>
                <div class="media-object-section">
                    <h5>And the world keeps spinning.</h5>
                </div>
              </div>
              <div class="media-object">
                <div class="media-object-section">
                    <img class="thumbnail" src="https://placehold.it/100">
                </div>
                <div class="media-object-section">
                    <h5>Cold hearted orb that rules the night.</h5>
                </div>
              </div>
          </div>
        </aside>
    </div>
  </div>
  {%endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="row">
    <div class="content">
      <h1 style="color: cadetblue">About</h1>

        <p>This project was built with</p>
        <ul>
          <li>Django (Web Framework - Python)</li>
          <li>Foundation (Css Framework)</li>
        </ul>
        <p>by Fatma Aşık</p>
    </div>
</div>



{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Blog</title>
    <link rel="stylesheet" href="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
  </head>
  <body>
    	<header>
          <div class="top-bar">
            <div class="row">
              <div class="top-bar-left">
                <ul class="menu">
                  <li class="logo"><a href="{% url 'home' %}">DjangoBlog</a></li>
                  <li class="menu-item"><a href="{% url 'home' %}">Home</a></li>
                  <li class="menu-item"><a href="{% url 'about' %}">About</a></li>
                </ul>
              </div>
              <div class="top-bar-right">
                <ul class="menu">
                  {% if user.is_authenticated %}
                    <li class="menu-item"><a href="{% url 'articles:create' %}">New Article</a></li>
                    <li class="menu-item">
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                          {% csrf_token %}
                          <button type="submit" class="logout-button">Logout</button>
                        </form>
                    </li>
                  {% else %}
                    <li class="menu-item"><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li class="menu-item"><a href="{% url 'accounts:signup' %}">Signup</a></li>
                  {% endif %}
                </ul>
              </div>
            </div>	
          </div>
        </header>
        <br>

    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
    <footer>
				<div class="row expanded callout secondary">
						
						<div class="medium-6 columns">
							<ul class="menu align-right">
									<li class="menu-text">Copyright © 2018 Fatma Aşık</li>
							</ul>
						</div>
				</div>
			</footer>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the homepage</h1>
    <p>Welcome to Djangoblog</p>
  </body>
</html>